VulnerablePopulation.find_or_create_by(description: "Retirados de la fuerza publica", order: 1)
VulnerablePopulation.find_or_create_by(description: "Grupos étnicos", order: 2)
VulnerablePopulation.find_or_create_by(description: "Población victima", order: 3)
VulnerablePopulation.find_or_create_by(description: "Personas LGBTIQ+", order: 4)
VulnerablePopulation.find_or_create_by(description: "Población migrante", order: 5)
VulnerablePopulation.find_or_create_by(description: "Personas en Proceso de reintegración y reincorporación", order: 6)
VulnerablePopulation.find_or_create_by(description: "Personas en condiciones de pobreza", order: 7)

SocioEconomicLevel.find_or_create_by(description: "Bajo-bajo", order: 1)
SocioEconomicLevel.find_or_create_by(description: "Bajo", order: 2)
SocioEconomicLevel.find_or_create_by(description: "Medio-bajo", order: 3)